### ISSUE TITLE
generateSchema task succeeds despite hibernate exception  

### ISSUE THREAD

**Issue by keykey7** [rmee/gradle-plugins#17]
com.github.rmee:jpa-schema-gen:0.8.20181201214153

Sample exception due to invalid entity class: generateSchema task still succeeds.
```
Exception in thread "Thread-412" java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
        at com.github.rmee.jpa.schemagen.GenerateSchemaTask.lambda$generate$0(GenerateSchemaTask.java:115)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.github.rmee.jpa.schemagen.GenerateSchemaTask.lambda$generate$0(GenerateSchemaTask.java:112)
        ... 1 more
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: DEMO-UNIT-GEN] Error performing schema management
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1016)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.generateSchema(EntityManagerFactoryBuilderImpl.java:926)
        at org.hibernate.jpa.HibernatePersistenceProvider.generateSchema(HibernatePersistenceProvider.java:161)
        at javax.persistence.Persistence.generateSchema(Persistence.java:87)
        ... 6 more
Caused by: org.hibernate.AnnotationException: Property of @IdClass not found in entity com.example.schema.PersistentXY: outputIndex
        at org.hibernate.cfg.AnnotationBinder.fillComponent(AnnotationBinder.java:2715)
        at org.hibernate.cfg.AnnotationBinder.bindIdClass(AnnotationBinder.java:2842)
        at org.hibernate.cfg.AnnotationBinder.mapAsIdClass(AnnotationBinder.java:1056)
        at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:784)
        at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:250)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:231)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:274)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:904)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.generateSchema(EntityManagerFactoryBuilderImpl.java:918)
        ... 8 more

BUILD SUCCESSFUL in 3s
```

**Comment by remmeier** [comment]
needs to be fixed, yes
